; example in the slide. 2 rooms, 3 balls, 1 gripper.

(define (problem pb1)
    (:domain gripper)
    (:requirements :strips)
  	(:objects roomA roomB Ball1 Ball2 Ball3 left)
	(:init 
		(room roomA)
		(room roomB)
		(ball Ball1)
		(ball Ball2)
		(ball Ball3)
		(gripper left)
		(at-robby roomA) 
		(free left) 
		(at Ball1 roomA)
		(at Ball2 roomA)
		(at Ball3 roomA))
	(:goal (and (at Ball1 roomB) 
		(at Ball2 roomB)
		(at Ball3 roomB)))
)
